schema_version = "2.0.0"
id = "GridGenerator"
version = "2.0.0"
name = "Grid Generator"
author = "José Marín"
tagline = "Customizable 3D Grids for Scientific Visualization in Blender"
description = """
v.2.0.0
new grids presets - 2Ds, 3D external, classic matlab grid and classic 3d coord system
new customizable parameters for each type
more units of measures
bugs correction 

"""
blender_version_min = "4.2.0"
license = ["free licensing"]
tags = ["3D", "Visualization", "Scientific", "Grid"]
type = "add-on"
maintainer = "José Marín <marinfarinajose@gmail.com>"
