schema_version = "1.0.0"
id = "GridGenerator"
version = "1.0.0"
name = "Grid Generator"
author = "José Marín"
tagline = "Customizable 3D Grids for Scientific Visualization in Blender"
description = """
v.1.0.0

This add-on extends Blender's functionality by enabling the creation and management of customizable 3D grids directly within the 3D viewport. Key features include:
- Generate 3D grid structures with adjustable dimensions and subdivisions
- Display coordinate numbers at each grid point
- Create visible edges with customizable thickness
- Apply emissive materials to make the grid stand out in renders
- Real-time updates for text and edge sizes
- Easily integrate 3D grids into scientific visualizations and data representations
- Streamlined UI for intuitive grid configuration and generation
"""
blender_version_min = "4.2.0"
license = ["free licensing"]
tags = ["3D", "Visualization", "Scientific", "Grid"]
type = "add-on"
maintainer = "José Marín <marinfarinajose@gmail.com>"